import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    selectLocation: 'Select Location',
    change: 'Change',
    confirmBookingTitle: 'Confirm Booking',
    confirmBookingMessage: 'Review your quote below. Confirm only when you\'re ready.',
    confirmProvider: 'Provider',
    confirmService: 'Service',
    confirmLocation: 'Location',
    confirmTotal: 'Total',
    bookingDeclined: 'Booking cancelled. You can send a new request anytime.',
    missingDetailsTitle: 'Still needed',
    clarificationTypeHint: 'Type your reply in the box below and press send.',
    yes: 'Yes',
    no: 'No',
    serviceNotAvailable: 'Sorry, our services are currently not available in {{loc}}. Please select another location.',
    dashboard: 'Dashboard',
    serviceAssistant: 'Service Assistant',
    appName: 'ServiceBazaar',
    loginTitle: 'Log in to your account',
    username: 'Username',
    password: 'Password',
    loginBtn: 'Login',
    welcome: 'Welcome back, Admin',
    whatService: 'Tell us what service do you need?',
    customService: 'Other (Describe manually in chat)',
    plumbing: 'Plumbing',
    electrical: 'Electrical',
    tutoring: 'Tutoring',
    beautician: 'Beautician',
    mechanic: 'Mechanic',
    moving: 'Moving',
    chatInit: 'Hi there! I am your AI service orchestrator. Tell me what you need help with.',
    placeholder: 'Type your service request...',
    thinking: 'Thinking...',
    currentLoc: 'Current Location',
    feedbackTitle: 'Service Lifecycle Feedback',
    feedbackPlaceholder: 'Describe your experience or lodge a complaint...',
    submitFeedback: 'Submit Feedback',
    fallbackMsg: 'We are connecting you securely. Please hold on a moment...',
    pollConnectionError: 'We\'re experiencing technical difficulties connecting to the service. Please check your internet connection.',
    islamabadOnlyTitle: 'We currently service only Islamabad',
    islamabadOnlyDesc: 'Our services are not yet available in Lahore, Karachi or any other area. Please continue with Islamabad.',
    proceedIslamabad: 'Proceed with Islamabad',
    pipeline1: 'Analyzing your request...',
    pipeline2: 'Checking availability...',
    pipeline3: 'Finalizing details...',
    requestTimeout: 'Request timed out. Please try again.',
    swarmErrorPrefix: 'Swarm Execution Error:',
    unknownIssue: 'Unknown execution issue.',
    bookingConfirmedToast: 'Booking confirmed — {{id}}',
    consultAssistant: 'Consult AI Assistant',
    viewMyBookings: 'View My Bookings',
    bookingConfirmedHeader: 'Booking Confirmed',
    serviceConfirmed: 'Service Confirmed!',
    bookingIdLabel: 'ID: {{id}}',
    yourProvider: 'Your Provider',
    whyChosen: 'Why they were chosen:',
    reliability: 'Reliability',
    rating: 'Rating',
    distanceScore: 'Distance Score',
    recencyScore: 'Recency Score',
    runnerUpNote: '{{runnerUp}} was closer, but {{provider}} was selected due to a higher reliability score for this specific task.',
    serviceDetails: 'Service Details',
    sector: 'Sector {{loc}}',
    unknown: 'Unknown',
    urgencyAsap: 'As soon as possible',
    urgencyScheduled: 'Scheduled',
    estimatedPricing: 'Estimated Pricing',
    viewAppointment: 'View Appointment',
    backToHome: 'Back to Home',
    kmAway: '{{km}} km away',
    labourCost: 'Labour & Service Cost',
    travelSurcharge: 'Travel Surcharge',
    bookingFee: 'Booking Fee',
    loyaltyDiscount: 'Loyalty Discount',
    totalAmount: 'Total Amount',
    bookingDetails: 'Booking Details',
    inProgress: 'In Progress',
    completed: 'Completed',
    liveTimeline: 'Live Timeline',
    timelineConfirmed: 'Booking Confirmed',
    timelineNotified: 'Provider Notified (SMS/WhatsApp)',
    timelineEnRoute: 'Provider En Route',
    timelineInProgress: 'Service In Progress',
    timelineCompleted: 'Job Completed',
    verifyingChecklist: 'Verifying service checklist...',
    sectorLabel: 'Sector: {{loc}}',
    urgencyLabel: 'Urgency: {{urgency}}',
    yourRequest: 'Your Request:',
    servicePricing: 'Service Pricing',
    rateFeedback: 'Rate & Feedback',
    rateFeedbackDesc: 'How was your experience? If there was an issue, our agentic system will resolve it automatically.',
    disputeHandled: 'Dispute Handled by AI',
    providerReputationUpdated: 'Provider Reputation Updated:',
    actionLabel: 'Action: {{action}}',
    reliabilityChange: 'Reliability: {{old}} → {{new}}',
    disputeFailed: 'Failed to lodge dispute. Admin notified.',
    assignedProvider: 'Assigned Provider',
    myBookings: 'My Bookings',
    noBookings: 'No recent bookings found.',
    serviceBooking: 'Service Booking',
    recent: 'Recent',
    orchestratorTraces: 'Orchestrator Traces',
    noTraces: 'No traces found.',
    tracesFetchError: 'Error fetching traces: {{msg}}',
    errorCardTitle: 'Error',
    serviceUnderstood: 'Service Understood',
    providerMatched: 'Provider Matched',
    estimatedPriceCard: 'Estimated Price',
    clarificationNeeded: 'Clarification needed.',
    statusConfirmed: 'CONFIRMED',
    statusCompleted: 'COMPLETED',
    statusPaymentHold: 'PAYMENT HOLD',
  },
  ur: {
    selectLocation: 'موقع منتخب کریں',
    change: 'تبدیل کریں',
    confirmBookingTitle: 'بکنگ کی تصدیق کریں',
    confirmBookingMessage: 'ذیل میں کوٹ دیکھیں۔ تیار ہونے پر تصدیق کریں۔',
    confirmProvider: 'فراہم کنندہ',
    confirmService: 'سروس',
    confirmLocation: 'مقام',
    confirmTotal: 'کل رقم',
    bookingDeclined: 'بکنگ منسوخ کر دی گئی۔ آپ کسی بھی وقت نئی درخواست بھیج سکتے ہیں۔',
    missingDetailsTitle: 'ابھی درکار',
    clarificationTypeHint: 'نیچے اپنا جواب لکھ کر بھیجیں۔',
    yes: 'جی ہاں',
    no: 'نہیں',
    serviceNotAvailable: 'معذرت، ہماری خدمات فی الحال {{loc}} میں دستیاب نہیں ہیں۔ براہ کرم کوئی اور مقام منتخب کریں۔',
    dashboard: 'ڈیش بورڈ',
    serviceAssistant: 'سروس اسسٹنٹ',
    appName: 'سروس بازار',
    loginTitle: 'اپنے اکاؤنٹ میں لاگ ان کریں',
    username: 'صارف نام',
    password: 'پاس ورڈ',
    loginBtn: 'لاگ ان کریں',
    welcome: 'خوش آمدید، ایڈمن',
    whatService: 'ہمیں بتائیں کہ آپ کو کس سروس کی ضرورت ہے؟',
    customService: 'دیگر (چیٹ میں خود لکھیں)',
    plumbing: 'پلمبنگ',
    electrical: 'بجلی کا کام',
    tutoring: 'ٹیوشن',
    beautician: 'بیوٹیشن',
    mechanic: 'میکینک',
    moving: 'سامان منتقل کرنا',
    chatInit: 'سلام! میں آپ کا اے آئی سروس آرکیسٹریٹر ہوں۔ بتائیں میں آپ کی کیا مدد کر سکتا ہوں۔',
    placeholder: 'اپنی سروس کی درخواست یہاں لکھیں...',
    thinking: 'سوچ رہا ہے...',
    currentLoc: 'موجودہ مقام',
    feedbackTitle: 'سروس لائف سائیکل فیڈ بیک',
    feedbackPlaceholder: 'اپنا تجربہ بیان کریں یا شکایت درج کریں...',
    submitFeedback: 'فیڈ بیک جمع کروائیں',
    fallbackMsg: 'سسٹم سے محفوظ رابطہ قائم کیا جا رہا ہے۔ براہ کرم انتظار کریں...',
    pollConnectionError: 'سرور تک رسائی ممکن نہیں۔ اپنا کنکشن اور بیک اینڈ چیک کریں۔',
    islamabadOnlyTitle: 'ہم فی الحال صرف اسلام آباد میں سروس دیتے ہیں',
    islamabadOnlyDesc: 'لاہور، کراچی یا دیگر علاقوں میں ابھی سروس دستیاب نہیں۔ براہ کرم اسلام آباد کے ساتھ آگے بڑھیں۔',
    proceedIslamabad: 'اسلام آباد کے ساتھ آگے بڑھیں',
    pipeline1: 'آپ کی درخواست کا تجزیہ ہو رہا ہے...',
    pipeline2: 'دستیابی چیک ہو رہی ہے...',
    pipeline3: 'تفصیلات مکمل ہو رہی ہیں...',
    requestTimeout: 'درخواست کا وقت ختم ہو گیا۔ دوبارہ کوشش کریں۔',
    swarmErrorPrefix: 'سسٹم کی خرابی:',
    unknownIssue: 'نامعلوم مسئلہ۔',
    bookingConfirmedToast: 'بکنگ کی تصدیق — {{id}}',
    consultAssistant: 'اے آئی اسسٹنٹ سے بات کریں',
    viewMyBookings: 'میری بکنگز دیکھیں',
    bookingConfirmedHeader: 'بکنگ کی تصدیق',
    serviceConfirmed: 'سروس کی تصدیق ہو گئی!',
    bookingIdLabel: 'آئی ڈی: {{id}}',
    yourProvider: 'آپ کا فراہم کنندہ',
    whyChosen: 'انہیں کیوں منتخب کیا گیا:',
    reliability: 'قابل اعتماد',
    rating: 'درجہ بندی',
    distanceScore: 'فاصلہ سکور',
    recencyScore: 'حالیہ سکور',
    runnerUpNote: '{{runnerUp}} قریب تھے، لیکن اس کام کے لیے {{provider}} کی زیادہ قابل اعتمادی کی وجہ سے منتخب ہوئے۔',
    serviceDetails: 'سروس کی تفصیلات',
    sector: 'سیکٹر {{loc}}',
    unknown: 'نامعلوم',
    urgencyAsap: 'جلد از جلد',
    urgencyScheduled: 'شیڈول شدہ',
    estimatedPricing: 'تخمینی قیمت',
    viewAppointment: 'اپائنٹمنٹ دیکھیں',
    backToHome: 'ہوم پر واپس',
    kmAway: '{{km}} کلومیٹر دور',
    labourCost: 'مزدوری اور سروس کی لاگت',
    travelSurcharge: 'سفر کا اضافی چارج',
    bookingFee: 'بکنگ فیس',
    loyaltyDiscount: 'وفاداری رعایت',
    totalAmount: 'کل رقم',
    bookingDetails: 'بکنگ کی تفصیلات',
    inProgress: 'جاری ہے',
    completed: 'مکمل',
    liveTimeline: 'لائیو ٹائم لائن',
    timelineConfirmed: 'بکنگ کی تصدیق',
    timelineNotified: 'فراہم کنندہ کو اطلاع (SMS/WhatsApp)',
    timelineEnRoute: 'فراہم کنندہ راستے میں',
    timelineInProgress: 'سروس جاری ہے',
    timelineCompleted: 'کام مکمل',
    verifyingChecklist: 'سروس چیک لسٹ کی تصدیق...',
    sectorLabel: 'سیکٹر: {{loc}}',
    urgencyLabel: 'فوریت: {{urgency}}',
    yourRequest: 'آپ کی درخواست:',
    servicePricing: 'سروس کی قیمت',
    rateFeedback: 'درجہ بندی اور فیڈ بیک',
    rateFeedbackDesc: 'آپ کا تجربہ کیسا رہا؟ اگر کوئی مسئلہ تھا تو ہمارا سسٹم خود حل کرے گا۔',
    disputeHandled: 'اے آئی نے تنازعہ حل کیا',
    providerReputationUpdated: 'فراہم کنندہ کی ساکھ اپ ڈیٹ:',
    actionLabel: 'عمل: {{action}}',
    reliabilityChange: 'قابل اعتماد: {{old}} ← {{new}}',
    disputeFailed: 'شکایت درج نہیں ہو سکی۔ ایڈمن کو اطلاع دی گئی۔',
    assignedProvider: 'تفویض شدہ فراہم کنندہ',
    myBookings: 'میری بکنگز',
    noBookings: 'کوئی حالیہ بکنگ نہیں ملی۔',
    serviceBooking: 'سروس بکنگ',
    recent: 'حالیہ',
    orchestratorTraces: 'آرکیسٹریٹر ٹریسز',
    noTraces: 'کوئی ٹریس نہیں ملی۔',
    tracesFetchError: 'ٹریس لوڈ کرنے میں خرابی: {{msg}}',
    errorCardTitle: 'خرابی',
    serviceUnderstood: 'سروس سمجھ آ گئی',
    providerMatched: 'فراہم کنندہ مل گیا',
    estimatedPriceCard: 'تخمینی قیمت',
    clarificationNeeded: 'مزید معلومات درکار ہے۔',
    statusConfirmed: 'تصدیق شدہ',
    statusCompleted: 'مکمل',
    statusPaymentHold: 'ادائیگی زیر التوا',
  },
};

export const LanguageProvider = ({ children }) => {
  const [selectedLocation, setSelectedLocation] = useState(null);
  const [locale, setLocale] = useState('en');

  const t = (key, params = {}) => {
    let str = translations[locale]?.[key] ?? translations.en[key] ?? key;
    Object.keys(params).forEach((p) => {
      str = str.replace(`{{${p}}}`, String(params[p]));
    });
    return str;
  };

  const toggleLanguage = () => {
    setLocale((prev) => (prev === 'en' ? 'ur' : 'en'));
  };

  const isRTL = locale === 'ur';

  return (
    <LanguageContext.Provider
      value={{ locale, t, toggleLanguage, setLocale, isRTL, selectedLocation, setSelectedLocation }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
